In [ ]:
# 1) Write a python program to display all the header tags from wikipedia.org

In [1]:
!pip install bs4
!pip install requests

Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py): started
  Building wheel for bs4 (setup.py): finished with status 'done'
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1271 sha256=d93b06b9ef0e61b59f44e7d1d81d26c066359734fbec96bd414632c70573b5be
  Stored in directory: c:\users\arun\appdata\local\pip\cache\wheels\73\2b\cb\099980278a0c9a3e57ff1a89875ec07bfa0b6fcbebb9a8cad3
Successfully built bs4
Installing collected packages: bs4
Successfully installed bs4-0.0.1

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2021.10.8)

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

In [2]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\programdata\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (1.26.7)

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

In [3]:
from bs4 import BeautifulSoup
import requests

In [6]:
page=requests.get('https://en.wikipedia.org/wiki/Main_Page')
page

In [7]:
soup=BeautifulSoup(page.content)
soup
header=[]
for i in soup.find_all(['h1', 'h2','h3','h4','h5','h6']):
    header.append(i.text)
header
import pandas as pd
df=pd.DataFrame({'Header':header})
df

                           Header
0                       Main Page
1            Welcome to Wikipedia
2   From today's featured article
3                Did you know ...
4                     In the news
5                     On this day
6        Today's featured picture
7        Other areas of Wikipedia
8     Wikipedia's sister projects
9             Wikipedia languages
10                Navigation menu
11                     \nSearch\n

In [ ]:
# 2)Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame.

In [8]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\programdata\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (1.26.7)

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

In [9]:
from bs4 import BeautifulSoup
import requests

In [10]:
page=requests.get('https://www.imdb.com/list/ls091520106/')
page

In [11]:
soup=BeautifulSoup(page.content)

In [12]:
titles=[]
for i in soup.find_all('h3',class_='lister-item-header'):
    titles.append(i.text.replace('\n'," "))
titles

[' 1. The Shawshank Redemption (1994) ',
 ' 2. The Godfather (1972) ',
 ' 3. The Godfather: Part II (1974) ',
 ' 4. The Dark Knight (2008) ',
 ' 5. 12 Angry Men (1957) ',
 " 6. Schindler's List (1993) ",
 ' 7. The Lord of the Rings: The Return of the King (2003) ',
 ' 8. Pulp Fiction (1994) ',
 ' 9. Il buono, il brutto, il cattivo (1966) ',
 ' 10. Fight Club (1999) ',
 ' 11. Joker (I) (2019) ',
 ' 12. The Lord of the Rings: The Fellowship of the Ring (2001) ',
 ' 13. Forrest Gump (1994) ',
 ' 14. Inception (2010) ',
 ' 15. The Empire Strikes Back (1980) ',
 ' 16. The Lord of the Rings: The Two Towers (2002) ',
 ' 17. The Matrix (1999) ',
 " 18. One Flew Over the Cuckoo's Nest (1975) ",
 ' 19. Goodfellas (1990) ',
 ' 20. Shichinin no samurai (1954) ',
 ' 21. Se7en (1995) ',
 ' 22. Cidade de Deus (2002) ',
 ' 23. La vita è bella (1997) ',
 ' 24. The Silence of the Lambs (1991) ',
 ' 25. Star Wars (1977) ',
 " 26. It's a Wonderful Life (1946) ",
 ' 27. Saving Private Ryan (1998) ',
 ' 28. Sen to Chihiro no kamikakushi (2001) ',
 ' 29. The Green Mile (1999) ',
 ' 30. Léon (1994) ',
 ' 31. Seppuku (1962) ',
 ' 32. Interstellar (2014) ',
 ' 33. The Usual Suspects (1995) ',
 ' 34. The Lion King (1994) ',
 ' 35. American History X (1998) ',
 ' 36. Back to the Future (1985) ',
 ' 37. The Pianist (2002) ',
 ' 38. Modern Times (1936) ',
 ' 39. Terminator 2: Judgment Day (1991) ',
 ' 40. The Intouchables (2011) ',
 ' 41. Psycho (1960) ',
 ' 42. Gladiator (2000) ',
 ' 43. City Lights (1931) ',
 ' 44. The Departed (2006) ',
 ' 45. Whiplash (2014) ',
 ' 46. Once Upon a Time in the West (1968) ',
 ' 47. The Prestige (2006) ',
 ' 48. Avengers: Endgame (2019) ',
 ' 49. Casablanca (1942) ',
 ' 50. Hotaru no haka (1988) ',
 ' 51. Rear Window (1954) ',
 ' 52. Nuovo Cinema Paradiso (1988) ',
 ' 53. Alien (1979) ',
 ' 54. Raiders of the Lost Ark (1981) ',
 ' 55. Memento (2000) ',
 ' 56. Apocalypse Now (1979) ',
 ' 57. The Great Dictator (1940) ',
 ' 58. The Lives of Others (2006) ',
 ' 59. Avengers: Infinity War (2018) ',
 ' 60. Django Unchained (2012) ',
 ' 61. Spider-Man: Into the Spider-Verse (2018) ',
 ' 62. The Shining (1980) ',
 ' 63. Paths of Glory (1957) ',
 ' 64. WALL·E (2008) ',
 ' 65. Sunset Blvd. (1950) ',
 ' 66. Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) ',
 ' 67. Mononoke-hime (1997) ',
 ' 68. Oldeuboi (2003) ',
 ' 69. Witness for the Prosecution (1957) ',
 ' 70. The Dark Knight Rises (2012) ',
 ' 71. Once Upon a Time in America (1984) ',
 ' 72. Gisaengchung (2019) ',
 ' 73. Aliens (1986) ',
 ' 74. American Beauty (1999) ',
 ' 75. Coco (I) (2017) ',
 ' 76. Kimi no na wa. (2016) ',
 ' 77. Braveheart (1995) ',
 ' 78. Das Boot (1981) ',
 ' 79. 3 Idiots (2009) ',
 ' 80. Taare Zameen Par (2007) ',
 ' 81. Star Wars: Episode VI - Return of the Jedi (1983) ',
 ' 82. Toy Story (1995) ',
 ' 83. Reservoir Dogs (1992) ',
 ' 84. Amadeus (1984) ',
 ' 85. Dangal (2016) ',
 ' 86. Good Will Hunting (1997) ',
 ' 87. Inglourious Basterds (2009) ',
 ' 88. M - Eine Stadt sucht einen Mörder (1931) ',
 ' 89. Requiem for a Dream (2000) ',
 ' 90. 2001: A Space Odyssey (1968) ',
 ' 91. Vertigo (1958) ',
 ' 92. Eternal Sunshine of the Spotless Mind (2004) ',
 ' 93. Citizen Kane (1941) ',
 ' 94. Full Metal Jacket (1987) ',
 ' 95. Jagten (2012) ',
 ' 96. North by Northwest (1959) ',
 ' 97. A Clockwork Orange (1971) ',
 ' 98. Snatch (2000) ',
 " 99. Le fabuleux destin d'Amélie Poulain (2001) ",
 ' 100. The Kid (1921) ']

In [13]:
year=[]
for i in soup.find_all('span',class_="lister-item-year text-muted unbold"):
    year.append(i.text)
year

['(1994)',
 '(1972)',
 '(1974)',
 '(2008)',
 '(1957)',
 '(1993)',
 '(2003)',
 '(1994)',
 '(1966)',
 '(1999)',
 '(I) (2019)',
 '(2001)',
 '(1994)',
 '(2010)',
 '(1980)',
 '(2002)',
 '(1999)',
 '(1975)',
 '(1990)',
 '(1954)',
 '(1995)',
 '(2002)',
 '(1997)',
 '(1991)',
 '(1977)',
 '(1946)',
 '(1998)',
 '(2001)',
 '(1999)',
 '(1994)',
 '(1962)',
 '(2014)',
 '(1995)',
 '(1994)',
 '(1998)',
 '(1985)',
 '(2002)',
 '(1936)',
 '(1991)',
 '(2011)',
 '(1960)',
 '(2000)',
 '(1931)',
 '(2006)',
 '(2014)',
 '(1968)',
 '(2006)',
 '(2019)',
 '(1942)',
 '(1988)',
 '(1954)',
 '(1988)',
 '(1979)',
 '(1981)',
 '(2000)',
 '(1979)',
 '(1940)',
 '(2006)',
 '(2018)',
 '(2012)',
 '(2018)',
 '(1980)',
 '(1957)',
 '(2008)',
 '(1950)',
 '(1964)',
 '(1997)',
 '(2003)',
 '(1957)',
 '(2012)',
 '(1984)',
 '(2019)',
 '(1986)',
 '(1999)',
 '(I) (2017)',
 '(2016)',
 '(1995)',
 '(1981)',
 '(2009)',
 '(2007)',
 '(1983)',
 '(1995)',
 '(1992)',
 '(1984)',
 '(2016)',
 '(1997)',
 '(2009)',
 '(1931)',
 '(2000)',
 '(1968)',
 '(1958)',
 '(2004)',
 '(1941)',
 '(1987)',
 '(2012)',
 '(1959)',
 '(1971)',
 '(2000)',
 '(2001)',
 '(1921)']

In [14]:
imdb_rating=[]
for i in soup.find_all('div',class_="ipl-rating-star small"):
    imdb_rating.append(i.text.replace('\n'," "))
imdb_rating

['        9.3 ',
 '        9.2 ',
 '        9 ',
 '        9 ',
 '        9 ',
 '        9 ',
 '        9 ',
 '        8.9 ',
 '        8.8 ',
 '        8.8 ',
 '        8.4 ',
 '        8.8 ',
 '        8.8 ',
 '        8.8 ',
 '        8.7 ',
 '        8.8 ',
 '        8.7 ',
 '        8.7 ',
 '        8.7 ',
 '        8.6 ',
 '        8.6 ',
 '        8.6 ',
 '        8.6 ',
 '        8.6 ',
 '        8.6 ',
 '        8.6 ',
 '        8.6 ',
 '        8.6 ',
 '        8.6 ',
 '        8.5 ',
 '        8.6 ',
 '        8.6 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.6 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.4 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.5 ',
 '        8.4 ',
 '        8.4 ',
 '        8.5 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.3 ',
 '        8.5 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.4 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.4 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ',
 '        8.3 ']

In [15]:
import pandas as pd
df=pd.DataFrame({'Movie Name':titles,'Year of Release':year,'Imdb_Rating':imdb_rating})
df

,Movie Name,Year of Release,Imdb_Rating
0,1. The Shawshank Redemption (1994),(1994),9.3
1,2. The Godfather (1972),(1972),9.2
2,3. The Godfather: Part II (1974),(1974),9
3,4. The Dark Knight (2008),(2008),9
4,5. 12 Angry Men (1957),(1957),9
...,...,...,...
95,96. North by Northwest (1959),(1959),8.3
96,97. A Clockwork Orange (1971),(1971),8.3
97,98. Snatch (2000),(2000),8.3
98,99. Le fabuleux destin d'Amélie Poulain (2001),(2001),8.3
99,100. The Kid (1921),(1921),8.3

In [ ]:
# 3)Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. name, rating, year of release) and make data frame

In [16]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\programdata\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.0.4)

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

In [17]:
from bs4 import BeautifulSoup
import requests

In [18]:
page=requests.get('https://www.imdb.com/list/ls056092300/?sort=user_rating,desc&st_dt=&mode=detail&page=1')
page

In [19]:
soup=BeautifulSoup(page.content)

In [20]:
movie_name=[]
year=[]
imdb_rating=[]
for i in soup.find_all('h3',class_='lister-item-header'):
    movie_name.append(i.text.replace('\n'," "))
movie_name
for i in soup.find_all('span',class_="lister-item-year text-muted unbold"):
    year.append(i.text)
year
for i in soup.find_all('div',class_="ipl-rating-star small"):
    imdb_rating.append(i.text.replace('\n',''))
imdb_rating
import pandas as pd
df=pd.DataFrame({'Movie Name':movie_name,'Year of Release':year,'Imdb_Rating':imdb_rating})
df

                           Movie Name Year of Release Imdb_Rating
0          1. Sagara Sangamam (1983)           (1983)         8.8
1    2. Goopy Gyne Bagha Byne (1969)           (1969)         8.7
2                  3. Nayakan (1987)           (1987)         8.6
3          4. Pushpaka Vimana (1987)           (1987)         8.6
4              5. Apur Sansar (1959)           (1959)         8.5
..                                ...             ...         ...
95                 96. Vanaja (2006)           (2006)         7.1
96            97. Amma Ariyan (1986)           (1986)         7.1
97               98. Enthiran (2010)           (2010)           7
98                99. Chandni (1989)           (1989)         6.7
99          100. Neecha Nagar (1946)           (1946)         6.7

[100 rows x 3 columns]

4) Write s python program to display list of respected former presidents of India(i.e. Name , Term of office) 
from https://presidentofindia.nic.in/former-presidents.ht

In [2]:
import pandas as pd   #to create dataframe
import requests       #to send the request to the URL
from bs4 import BeautifulSoup #to get the content in the form of HTML
import numpy as np

In [3]:
url = 'https://presidentofindia.nic.in/former-presidents.htm'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

In [4]:
president_name=[]
term_of_office = []

In [5]:
president_data = soup.findAll('div', attrs= {'class': 'presidentListing'})


for store in president_data:
    name = store.h3
    president_name.append(name)
    
    year_of_join = store.h3.find('span', class_ = 'terms')
    term_of_office.append(year_of_join)

In [6]:
data = pd.DataFrame({'name': president_name, 'term': term_of_office})

In [7]:
data.head(100)

                                             name  term
0             [Shri Pranab Mukherjee (1935-2020)]  None
1   [Smt Pratibha Devisingh Patil (birth - 1934)]  None
2            [DR. A.P.J. Abdul Kalam (1931-2015)]  None
3            [Shri K. R. Narayanan (1920 - 2005)]  None
4           [Dr Shankar Dayal Sharma (1918-1999)]  None
5               [Shri R Venkataraman (1910-2009)]  None
6                  [Giani Zail Singh (1916-1994)]  None
7         [Shri Neelam Sanjiva Reddy (1913-1996)]  None
8          [Dr. Fakhruddin Ali Ahmed (1905-1977)]  None
9      [Shri Varahagiri Venkata Giri (1894-1980)]  None
10                 [Dr. Zakir Husain (1897-1969)]  None
11     [Dr. Sarvepalli Radhakrishnan (1888-1975)]  None
12             [Dr. Rajendra Prasad (1884-1963) ]  None

5) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape: a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating. b) Top 10 ODI Batsmen along with the records of their team and rating. c) Top 10 ODI bowlers along with the records of their team and rating

a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.

In [2]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\programdata\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2021.10.8)

WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

In [3]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
page=requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
soup=BeautifulSoup(page.content)

In [4]:
team = soup.find_all("span",class_='u-hide-phablet')
team_name = []
for i in team:
    team_name.append(i.text)
matches = [] 
points = [] 
ratings = [] 
new_list = []
for i in soup.find_all("td",class_='rankings-block__banner--matches'): 
    matches.append(i.text)
for i in soup.find_all("td",class_='rankings-block__banner--points'):
    points.append(i.text)
for i in soup.find_all("td",class_='rankings-block__banner--rating u-text-right'):
    ratings.append(i.text.replace("\n",""))
for i in soup.find_all("td",class_='table-body__cell u-center-text'):
    new_list.append(i.text)
for i in range(0,len(new_list)-1,2):
    matches.append(new_list[i]) 
    points.append(new_list[i+1])
for i in soup.find_all("td",class_='table-body__cell u-text-right rating'):
    ratings.append(i.text)
icc=pd.DataFrame({})
icc['Team_name']=team_name[:10]
icc['Matches']=matches[:10]
icc['Points']=points[:10]
icc['Ratings']=ratings[:10]
icc

,Team_name,Matches,Points,Ratings
0,New Zealand,12,"1,505",125 ...
1,England,19,"2,353",124
2,Australia,18,"1,929",107
3,India,22,"2,304",105
4,Pakistan,16,"1,635",102
5,South Africa,19,"1,872",99
6,Bangladesh,24,"2,275",95
7,Sri Lanka,24,"2,086",87
8,West Indies,26,"1,885",73
9,Afghanistan,15,986,66

b) Top 10 ODI Batsmen along with the records of their team and rating.

In [7]:
page = requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting')
soup = BeautifulSoup(page.content)
players = [] 
team_name = [] 
rating = []

In [8]:
for i in soup.find_all("div",class_='rankings-block__banner--name-large'): 
    players.append(i.text)

In [9]:
for i in soup.find_all("div",class_='rankings-block__banner--nationality'): 
    team_name.append(i.text.replace("\n",""))

In [10]:
for i in soup.find_all("div",class_='rankings-block__banner--rating'): 
    rating.append(i.text)

In [11]:
for i in soup.find_all("td",class_='table-body__cell rankings-table__name name'):
    for j in i.find_all('a'):
        players.append(j.text)

In [12]:
for i in soup.find_all("span",class_='table-body__logo-text'): 
    team_name.append(i.text)

In [13]:
for i in soup.find_all("td",class_='table-body__cell rating'): 
    rating.append(i.text)

In [14]:
Batsmen=pd.DataFrame({})
Batsmen['Player']=players[:10]
Batsmen['Team']=team_name[:10]
Batsmen['Rating']=rating[:10]
Batsmen

                  Player                     Team Rating
0             Babar Azam  PAK                        891
1            Virat Kohli                      IND    811
2            Imam-ul-Haq                      PAK    795
3           Rohit Sharma                      IND    791
4        Quinton de Kock                       SA    789
5         Jonny Bairstow                      ENG    775
6            Ross Taylor                       NZ    775
7  Rassie van der Dussen                       SA    769
8           David Warner                      AUS    750
9            Aaron Finch                      AUS    745

c) Top 10 ODI bowlers along with the records of their team and rating

In [15]:
page = requests.get("https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling")
soup = BeautifulSoup(page.content)

In [16]:
players = [] 
team_name = []  
rating = []

In [17]:
for i in soup.find_all("div",class_='rankings-block__banner--name-large'): 
    players.append(i.text)

In [18]:
for i in soup.find_all("div",class_='rankings-block__banner--nationality'): 
    team_name.append(i.text.replace("\n",""))

In [19]:
for i in soup.find_all("div",class_='rankings-block__banner--rating'): 
    rating.append(i.text)

In [20]:
for i in soup.find_all("td",class_='table-body__cell rankings-table__name name'):
    for j in i.find_all('a'):
        players.append(j.text)

In [21]:
for i in soup.find_all("span",class_='table-body__logo-text'): 
    team_name.append(i.text)

In [22]:
for i in soup.find_all("td",class_='table-body__cell rating'): 
    rating.append(i.text)

In [23]:
bowlers=pd.DataFrame({})
bowlers['Player']=players[:10]
bowlers['Team']=team_name[:10]
bowlers['Rating']=rating[:10]
bowlers

             Player                    Team Rating
0       Trent Boult  NZ                        726
1      Chris Woakes                     ENG    700
2    Josh Hazlewood                     AUS    698
3        Matt Henry                      NZ    683
4  Mujeeb Ur Rahman                     AFG    681
5    Jasprit Bumrah                     IND    679
6    Shaheen Afridi                     PAK    671
7      Mehedi Hasan                     BAN    661
8   Shakib Al Hasan                     BAN    657
9       Rashid Khan                     AFG    650

6) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape: a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating. b) Top 10 women’s ODI Batting players along with the records of their team and rating. c) Top 10 women’s ODI all-rounder along with the records of their team and rating

a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.

In [24]:
page = requests.get("https://www.icc-cricket.com/rankings/womens/team-rankings/odi")
soup = BeautifulSoup(page.content)
womens_team = soup.find_all("span",class_='u-hide-phablet')
womens_team_name = []
for i in womens_team:
    womens_team_name.append(i.text)
womens_matches = [] 
womens_points = [] 
womens_ratings = [] 
womens_new_list = [] 
for i in soup.find_all("td",class_='rankings-block__banner--matches'): 
    womens_matches.append(i.text)
for i in soup.find_all("td",class_='rankings-block__banner--points'):
    womens_points.append(i.text)
for i in soup.find_all("td",class_='rankings-block__banner--rating u-text-right'):
    womens_ratings.append(i.text.replace("\n",""))
for i in soup.find_all("td",class_='table-body__cell u-center-text'):
    womens_new_list.append(i.text)
for i in range(0,len(womens_new_list)-1,2):
    womens_matches.append(womens_new_list[i]) 
    womens_points.append(womens_new_list[i+1])
for i in soup.find_all("td",class_='table-body__cell u-text-right rating'):
    womens_ratings.append(i.text)
womens_icc=pd.DataFrame({})
womens_icc['Team_name']=womens_team_name[:10]
womens_icc['Matches']=womens_matches[:10]
womens_icc['Points']=womens_points[:10]
womens_icc['Ratings']=womens_ratings[:10]
womens_icc

,Team_name,Matches,Points,Ratings
0,Australia,29,"4,840",167 ...
1,South Africa,28,"3,504",125
2,England,30,"3,533",118
3,India,29,"2,878",99
4,New Zealand,31,"3,030",98
5,West Indies,28,"2,481",89
6,Bangladesh,12,936,78
7,Pakistan,26,"1,752",67
8,Ireland,5,240,48
9,Sri Lanka,5,233,47

b) Top 10 women’s ODI Batting players along with the records of their team and rating.

In [25]:
page = requests.get("https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting")
soup = BeautifulSoup(page.content)
players = [] 
team_name = [] 
rating = [] 
for i in soup.find_all("div",class_='rankings-block__banner--name-large'): 
    players.append(i.text)
for i in soup.find_all("div",class_='rankings-block__banner--nationality'): 
    team_name.append(i.text.replace("\n",""))
for i in soup.find_all("div",class_='rankings-block__banner--rating'): 
    rating.append(i.text)
for i in soup.find_all("td",class_='table-body__cell rankings-table__name name'):
    for j in i.find_all('a'):
        players.append(j.text)
for i in soup.find_all("span",class_='table-body__logo-text'):
    team_name.append(i.text)
for i in soup.find_all("td",class_='table-body__cell rating'): 
    rating.append(i.text)
top_players=pd.DataFrame({})
top_players['Player']=players[:10]
top_players['Team']=team_name[:10]
top_players['Rating']=rating[:10]
top_players

              Player                     Team Rating
0       Alyssa Healy  AUS                        785
1     Natalie Sciver                      ENG    750
2        Beth Mooney                      AUS    748
3    Laura Wolvaardt                       SA    722
4        Meg Lanning                      AUS    710
5     Rachael Haynes                      AUS    701
6        Mithali Raj                      IND    686
7  Amy Satterthwaite                       NZ    681
8    Smriti Mandhana                      IND    669
9     Tammy Beaumont                      ENG    659

c) Top 10 women’s ODI all-rounder along with the records of their team and rating

In [26]:
page = requests.get("https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder")


soup = BeautifulSoup(page.content)
players = [] 
team_name = []  
rating = []  
for i in soup.find_all("div",class_='rankings-block__banner--name-large'): 
    players.append(i.text)
for i in soup.find_all("div",class_='rankings-block__banner--nationality'): 
    team_name.append(i.text.replace("\n",""))
for i in soup.find_all("div",class_='rankings-block__banner--rating'): 
    rating.append(i.text)
for i in soup.find_all("td",class_='table-body__cell rankings-table__name name'):
    for j in i.find_all('a'):
        players.append(j.text)
for i in soup.find_all("span",class_='table-body__logo-text'): 
    team_name.append(i.text)
for i in soup.find_all("td",class_='table-body__cell rating'): 
    rating.append(i.text)
all_rounder=pd.DataFrame({})
all_rounder['Player']=players[:10]
all_rounder['Team']=team_name[:10]
all_rounder['Rating']=rating[:10]
all_rounder

             Player                     Team Rating
0    Natalie Sciver  ENG                        393
1      Ellyse Perry                      AUS    374
2    Marizanne Kapp                       SA    359
3   Hayley Matthews                       WI    338
4       Amelia Kerr                       NZ    335
5  Ashleigh Gardner                      AUS    269
6     Deepti Sharma                      IND    249
7     Jess Jonassen                      AUS    245
8   Katherine Brunt                      ENG    221
9    Jhulan Goswami                      IND    217

7) Write a python program to scrape mentioned news details from https://www.cnbc.com/world/?region=world :
i) Headline
ii) Time
iii) News Link

In [8]:
import pandas as pd   #to create dataframe
import requests       #to send the request to the URL
from bs4 import BeautifulSoup #to get the content in the form of HTML
import numpy as np  # to count the values (in our case)

8) Write a python program to scrape the details of most downloaded articles from AI in last 90 days.
https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles
Scrape below mentioned details :
i) Paper Title
ii) Authors
iii) Published Date
iv) Paper URL

9) Write a python program to scrape mentioned details from dineout.co.in :
i) Restaurant name
ii) Cuisine
iii) Location
iv) Ratings
v) Image URL

In [9]:
import pandas as pd   
import requests      
from bs4 import BeautifulSoup 
import numpy as np

In [10]:
url = 'https://www.dineout.co.in/delhi-restaurants/welcome-back'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

In [11]:
resturant_name = []
cuisine = []
location = []
rating = []
image=[]

In [12]:
resturant_data = soup.findAll('div', attrs= {'class': 'restnt-card resturant'})

#calling one by one using for loop
for store in resturant_data:
    name = store.h3.a.text
    resturant_name.append(name)
    
    rate = store.find('div', class_ = 'restnt-rating rating-4').text.replace('\n', '')
    rating.append(rate)
    
    location_name = store.find('div', class_ = 'restnt-loc ellipsis').text.replace('\n', '')
    locaion.append(location_name)

In [13]:
resturant_DF = pd.DataFrame({'Name of resturant': resturant_name, 'location_of_resturant': location, 'resturant Rating': rating})

In [14]:
resturant_DF.head()

Empty DataFrame
Columns: [Name of resturant, location_of_resturant, resturant Rating]
Index: []

10) Write a python program to scrape the details of top publications from Google Scholar from
https://scholar.google.com/citations?view_op=top_venues&hl=en
i) Rank
ii) Publication
iii) h5-index
iv) h5-median